### ISSUE TITLE
Create KRS-784 servo diagram with dimension labels

### ISSUE THREAD

**Issue by Chana030102** [pdx-robotics/Arduino_KHR-1#10]
We need to get dimensions of the servos on KHR-1 and draw it out on a diagram. This will be used as reference for future 3D modeling projects for parts/mounts.  Preferably in millimeters (mm). Be sure to also get the small tab sticking out on it. Push diagram to 'hardware' branch.

**Comment by jakechung42** [comment]
Jordan made the 3D model and I made the blueprint for it. Everything has been uploaded to branch.
