### ISSUE TITLE
Create diagram of HR-SC04 with dimensions

### ISSUE THREAD

**Issue by Chana030102** [pdx-robotics/Arduino_KHR-1#11]
Make a diagram for the Ultrasonic Sensor with dimensions for the board. If a component on the board sticks out a significant amount, it should also be measured and documented on the diagram as well. Push diagram to 'hardware' branch.

**Comment by jakechung42** [comment]
@Jordanb716 did you ever finish this? I remember seeing a blueprint for this sometimes ago.

**Comment by Jordanb716** [comment]
I took photos with measurements, but then forgot to upload them iirc, and they died when my previous phone did.

**Comment by jakechung42** [comment]
alright I'll make a model for the sensor. Should be easy to do.

**Comment by jakechung42** [comment]
If anyone wants to learn 3D modeling, or measuring dimensions, I can use this assignment to help you. The HR-SC04 is simple enough that we can get it done easily and quickly.

**Comment by Chana030102** [comment]
@jakechung42 this is low priority, so let's go ahead and leave this task as an opportunity for anyone new to 3D modeling.

**Comment by williamVbrines** [comment]
I am going to close this because there is no current plan to use the HR-SC04.
