### ISSUE TITLE
Modify files for consistency in documentation

### ISSUE THREAD

**Issue by Chana030102** [pdx-robotics/Arduino_KHR-1#12]
[2018/10/08] the [feature/semaphore](https://github.com/pdx-robotics/Arduino_KHR-1/tree/feature/semaphore) branch has the most work done on it and we will be merging that to master soon. Please make the changes mentioned below by branching off [feature/semaphore](https://github.com/pdx-robotics/Arduino_KHR-1/tree/feature/semaphore) and making a pull request back into "feature/semaphore".

Several things that were not planned out well in the beginning of this project need to be changed for better consistency:
- [x] Servo channel diagram reference image should match what's in code. (cause that's what it's for)
- [x] Change header and cpp files from "KHR_1" to "Arduino_KHR-1" to match repo name
- [x] Modify README.md accordingly

**Comment by Chana030102** [comment]
@williamVbrines Please refer to my updated comment at the top and my comment on #31 about working on this issue. Thanks!

**Comment by williamVbrines** [comment]
Thank you for the for the update I will make sure to make a branch off features/ semaphore and collaborate with @halyngoc in the future. However, who do I contact to review changes when making a pull request you or @halyngoc.

**Comment by halyngoc** [comment]
Quoting [my comment](https://github.com/pdx-robotics/Arduino_KHR-1/pull/25#issuecomment-427985433) from #25:
> I've noticed that master is too outdated compared to this branch which makes working on other issues more difficult. So I'll look into getting this merged as soon as possible.

@williamVbrines, you can ask me or @Chana030102 to review your PR, but I'm not authorized to merge it.

**Comment by halyngoc** [comment]
> - [ ] Servo channel diagram reference image should match what's in code. (cause that's what it's for)

> - [ ] Modify README.md accordingly

@Chana030102 I saw you already made commits related to these tasks. Can we check them off?

**Comment by halyngoc** [comment]
I noticed just now but it's "Arduino_KHR-1" not "Arduino_KHR1"
I feel bad for @williamVbrines 😃

**Comment by williamVbrines** [comment]
Don't worry got the header and cpp file changed to the right name now.
