### ISSUE TITLE
Inconsistent power issues

### ISSUE THREAD

**Issue by Chana030102** [pdx-robotics/Arduino_KHR-1#24]
Most of the time, none of the servos get powered when we upload the semaphore program. Occasionally it is possible to power one servo at a time by writing to each individually, but this is also very inconsistent. Sometimes, all the servos will work. 

Connections and parts on the PCB need to be checked for any damage or problems.

**Comment by jakechung42** [comment]
I figured that it's the hot and ground wires are touching. I isolated the 2 wires and I haven't seen the issue coming back yet so closing it for now.
