### ISSUE TITLE
Repair circuit board and conduct inspection for further damages

### ISSUE THREAD

**Issue by jakechung42** [pdx-robotics/Arduino_KHR-1#27]
KHR-1 is damaged from the accident at our general meeting. From initial inspection, it shows that the Arduino, the circuit board power wire and 4 servos are damaged. This issue it to replace, repair and investigate whether or not more parts need to be replaced for the circuit board.

**Comment by jakechung42** [comment]
Note that the circuit board has to be replaced or repaired before the servos in order to test the new servos and to make sure that only 4 servos are damaged.

**Comment by jakechung42** [comment]
@Chana030102 Hey Aaron, can you make a quick sketch for the connection of the Arduino to the Driver? Can I get that by Friday? I remember that you made me one but I can't find it. Make sure the upload it to the appropriate branch also so I don't have to ask you again in the future. Thanks.

**Comment by jakechung42** [comment]
just a quick sketch is fine, doesn't have to be fancy.

**Comment by Chana030102** [comment]
@jakechung42 There is already one in the "feature/semaphore" branch. Sketch is located [here](https://github.com/pdx-robotics/Arduino_KHR-1/blob/feature/semaphore/examples/SerialWrite_KHR1/SerialWrite_KHR1.ino).

**Comment by jakechung42** [comment]
> 
> 
> @jakechung42 There is already one in the "feature/semaphore" branch. Sketch is located [here](https://github.com/pdx-robotics/Arduino_KHR-1/blob/feature/semaphore/examples/SerialWrite_KHR1/SerialWrite_KHR1.ino).

sorry when I said sketch, I mean drawing. I guess I shouldn't use the word sketch from now on just in case.

**Comment by williamVbrines** [comment]
Repaired circuit board and Arduino. Damages included 4 servos CH3 CH6 CH9 CH10 and small damage to the port on the Arduino. See issue #26 fo report on busted servos.

**Comment by halyngoc** [comment]
Reopen because of @jakechung42's [comment](https://github.com/pdx-robotics/Arduino_KHR-1/issues/26#issuecomment-428442016):

> @williamVbrines hold off on closing this one. I want to calibrate the servos first before we close this.

**Comment by jakechung42** [comment]
@williamVbrines if you have calibrated the servos and make sure that they are working, go ahead and close this issue and along with issue #26
