### ISSUE TITLE
Update KHR-1's backpack to a newer design that is easier to install

### ISSUE THREAD

**Issue by jakechung42** [pdx-robotics/Arduino_KHR-1#28]
This issue is for upgrading KHR-1's backpack with a more modern, stylish look, and address the following issues: 

- [x] some tolerances are not correct
- [x] the backpack is difficult to assemble
- [x] no clear instruction on how to assemble
- [x] the backpack is too big that it is tend to be intrusive when KHR-1 is serviced
- [x] widen opening for Arduino USB port

The above are the issues so far for KHR-1's backpack. This thread can be updated to include more unexpected issues.

**Comment by williamVbrines** [comment]
If someone prints it I can design it.
