### ISSUE TITLE
Incorrect and jittery servo movements

### ISSUE THREAD

**Issue by Chana030102** [pdx-robotics/Arduino_KHR-1#3]
**Issue in regards to library version in branch feature/semaphore**

Running previously working functions with this version of the library seems to write values that differ from what we want in the code. Servos move in very jittery and also random directions even though we are writing the same values over and over again. 

It is suspected that the complex object used to control KHR-1 in this version is the cause. Running the previous version from master still works okay. Tested master and confirmed working as of 2018-05-25 at 8:40pm. This also confirms that damaged hardware (if any at all) was not the cause of incorrect servo movements.

**Comment by halyngoc** [comment]
Movements are normal now. Problem fixed.
