### ISSUE TITLE
Inventory spare parts for KHR-1

### ISSUE THREAD

**Issue by jakechung42** [pdx-robotics/Arduino_KHR-1#30]
Need to perform an inventory for the spare parts for KHR-1 in case we need to order more. The following items will be inventoried:

- [x] Servos
- [x] Broken servos 
- [x] Anything related to the skeleton of KHR-1
- [x] Servo attachments

**Comment by williamVbrines** [comment]
Completed inventory of the spare parts of KHR-1
Branch #35 adds a list with the following in hardware/KHR-1_Inventory.txt.

This list does not include items on the robot.
list last updated on October 10, 2018

Item - quantity
- Servos - 7 plastic gear, 2 metal gear, 8 Broken 
- Servo attachments - 23
- 6.0V 750mah battery pack - 1
- 4AA battery pack - 5
- sonar sensor -2
- pca9685 servo driver - 1
- arduino - 1
- Universal AC adaptor - 1
