### ISSUE TITLE
Change the order of Pose's members

### ISSUE THREAD

**Issue by halyngoc** [pdx-robotics/Arduino_KHR-1#38]
_Originally from #25_

> Currently the order is left arm, left leg, right arm, right leg. I want to change it to left arm, right arm, left leg, right leg to make it more readable.

As I said in https://github.com/pdx-robotics/Arduino_KHR-1/pull/25#issuecomment-427985433 I'm making this a separate issue to take some work off of #25. I already have the code for it and I'm just waiting for that PR to merge before I push this.

**Comment by Chana030102** [comment]
Change has been made and merged.
