### ISSUE TITLE
Design and print relay board

### ISSUE THREAD

**Issue by Chana030102** [pdx-robotics/Arduino_KHR-1#8]
Create a relay board for servos on KHR-1 to interact with the controlling harware

**Comment by Chana030102** [comment]
After working with @jakechung42 we have successfully gotten the Servo Driver PCA9685 to work properly. A prototype board is being soldered by Jake and Aaron will be making a schematic for when we need a more official board printed.

**Comment by jakechung42** [comment]
I'm gonna close this one since we are going with the soldered board now. @Chana030102
